### ISSUE TITLE
Add docker & docker-compose

### ISSUE THREAD

**Issue by linusromland** [linusromland/ContinuumCI#11]

**Comment by Arnab7456** [comment]
can you please elaborate the issue , i want to contribute .

**Comment by linusromland** [comment]
> 
Thank you for your interest in contributing to ContinuumCI. Unfortunately, at the moment this is a school assignment and I am unable to accept contributions. However, I do appreciate your offer and I would love to have your help in the future. If you'd like, feel free to check back in approximately 2 months after the assignment is completed. At that time, I plan on continuing development and I would welcome any contributions you could make. Thank you again for your interest.

**Comment by linusromland** [comment]
@Arnab7456 :
Thank you for your interest in contributing to ContinuumCI. Unfortunately, at the moment this is a school assignment and I am unable to accept contributions. However, I do appreciate your offer and I would love to have your help in the future. If you'd like, feel free to check back in approximately 2 months after the assignment is completed. At that time, I plan on continuing development and I would welcome any contributions you could make. Thank you again for your interest.

**Comment by linusromland** [comment]
will be resolved by #27
